(function() {
  if (document.getElementById('dashboard-guide-widget')) return;
  const css = `
    #dashboard-guide-widget .guide-fab { position:fixed; right:18px; bottom:18px; z-index:9998; border:none; border-radius:999px; padding:11px 15px; background:#378add; color:#fff; font-weight:700; box-shadow:0 8px 24px rgba(0,0,0,.22); cursor:pointer; }
    #dashboard-guide-widget .guide-backdrop { position:fixed; inset:0; background:rgba(0,0,0,.45); z-index:9999; display:none; align-items:center; justify-content:center; padding:18px; }
    #dashboard-guide-widget .guide-modal { width:min(860px, 100%); max-height:88vh; overflow:auto; background:var(--bg, #fff); color:var(--text, #111); border:1px solid var(--border, rgba(0,0,0,.1)); border-radius:16px; box-shadow:0 16px 48px rgba(0,0,0,.35); }
    #dashboard-guide-widget .guide-head { position:sticky; top:0; background:var(--bg, #fff); display:flex; justify-content:space-between; align-items:center; gap:12px; padding:14px 16px; border-bottom:1px solid var(--border, rgba(0,0,0,.1)); }
    #dashboard-guide-widget .guide-head strong { font-size:16px; }
    #dashboard-guide-widget .guide-close { border:1px solid var(--border2, rgba(0,0,0,.18)); background:transparent; color:var(--text, #111); border-radius:8px; padding:6px 10px; cursor:pointer; }
    #dashboard-guide-widget .guide-body { padding:14px 16px 20px; line-height:1.65; }
    #dashboard-guide-widget .guide-section { background:var(--bg2, #f6f7f8); border-radius:12px; padding:13px 14px; margin:10px 0; }
    #dashboard-guide-widget .guide-section h2 { font-size:15px; margin:0 0 6px; }
    #dashboard-guide-widget .guide-section ul { margin:0; padding-left:1.25em; }
    #dashboard-guide-widget .guide-section li { margin:5px 0; }
    #dashboard-guide-widget .guide-note { color:var(--text2, #555); font-size:12px; margin:8px 0 12px; }
    #dashboard-guide-widget .guide-link { display:inline-block; margin-top:8px; color:#378add; text-decoration:none; font-size:13px; }
  `;
  const html = `<section class="guide-section"><h2>ã¾ãè¦ãé çª</h2><ul><li>â  ãã¼ã¿ç¶æ â â¡ ç¾å¨ä¾¡æ ¼ â â¢ ã¨ã³ããªã¼å¤å® â â£ ã¨ã³ããªã¼æ ¹æ  â â¤ ã¹ã³ã¢åè¨³ â â¥ æåãã»å©ç¢ºã»æ¨å¥¨æ°é â â¦ ãã£ã¼ãã»ææ¨ â â§ ç·æ¬ã³ã¡ã³ã ã®é ã§ç¢ºèªãã¾ãã</li><li>æ£ããã¾ã§ã¯ãå¤å® â æ ¹æ  â æåããã®3ã¤ãä¸­å¿ã«è¦ãã°OKã§ãã</li></ul></section>
<section class="guide-section"><h2>ãã¼ã¿ç¶æã®è¦æ¹</h2><ul><li>CoinGecko / Coincheck / bitFlyer ã®ä¾¡æ ¼ãã¼ã¿ãªããåºæ¬çã«ã¯ç¾å¨ä¾¡æ ¼ãä½¿ãã¦ããç¶æã§ãã</li><li>ãç´è¿æåãã¼ã¿ããåèå¤ããåºã¦ããã¨ãã¯ææ°ä¾¡æ ¼ã§ã¯ãªãå¯è½æ§ããããããæ°è¦ã¨ã³ããªã¼å¤æ­ã¯æéã«ãã¦ãã ããã</li></ul></section>
<section class="guide-section"><h2>ã¨ã³ããªã¼å¤å®</h2><ul><li>ð¢ å¼·æ°ï¼æ¡ä»¶ãæ¯è¼çããã£ã¦ããç¶æããã ããçµ¶å¯¾ã«è²·ããã§ã¯ãªããå¥ãåè£ã¨ãã¦è¦ãæ®µéã§ãã</li><li>ð¡ æ¤è¨ï¼æªãã¯ãªããæ±ºå®æãä¸è¶³ãæ¼ãç®ãåºæ¥é«å¢å ãMAç¶­æããã¬ã¤ã¯å®çãå¾ã¤å ´é¢ã§ãã</li><li>ð´ è¦éãï¼åªä½æ§ãä½ãç¶æãå¥ããªãå¤æ­ãã§ããæç¹ã§ååä¾¡å¤ãããã¾ãã</li></ul></section>
<section class="guide-section"><h2>ã¨ã³ããªã¼æ ¹æ ã®èª­ã¿æ¹</h2><ul><li>æç« ã¯ãä»ã©ãããå ´é¢ãããå¥½ææããæ³¨æç¹ãã®3ã¤ã«åãã¦èª­ã¿ã¾ãã</li><li>å¥½ææãå¤ãã¦ããæ³¨æç¹ã«ãã¬ã¸ã¹ã¿ã³ã¹ãè¿ãããRRãæªããããã©ãé«ãããããå ´åã¯æ°éãè½ã¨ããè¦éããæ¤è¨ãã¾ãã</li></ul></section>
<section class="guide-section"><h2>ã¹ã³ã¢åè¨³ã®è¦æ¹</h2><ul><li>MAããã©ã¹ãªãç­æãã¬ã³ããä¸åããMACDããã©ã¹ãªãå¢ããè²·ãæ¹åã§ãã</li><li>RSIãåºæ¥é«ããµãã¬ã¸ããã©ãRRããã¤ãã¹ãªãããã®é ç®ãã¨ã³ããªã¼ã®å¼±ç¹ã§ããç¹ã«RRãæªãå ´åã¯ç¡çã«å¥ããªãå¤æ­ãå¤§åã§ãã</li></ul></section>
<section class="guide-section"><h2>ã©ãã§è²·ããã©ãã§å£²ãã</h2><ul><li>è²·ãåè£ã¯ãã¨ã³ããªã¼ãè¡¨ç¤ºãã¾ãã¯ãµãã¼ã/MAä»è¿ã§ãã</li><li>å£²ãåè£ã¯ãå©ç¢ºãè¡¨ç¤ºãã¾ãã¯ã¬ã¸ã¹ã¿ã³ã¹ä»è¿ã§ãã</li><li>éããå ´æã¯ãæåããè¡¨ç¤ºã§ããè²·ã£ã¦ããèããã®ã§ã¯ãªããè²·ãåã«å¿ãæ±ºãã¾ãã</li></ul></section>
<section class="guide-section"><h2>æåãã»å©ç¢ºã»æ¨å¥¨æ°é</h2><ul><li>æ³å®è³éã¨è¨±å®¹æå¤±ããã1åãããã®æå¤±ä¸éãæ±ºãã¾ããä¾ï¼100ä¸åã®1%ãªã1ä¸åã¾ã§ã</li><li>æ¨å¥¨æ°éã¯ãæå¤§ã§ããã®ãããã¾ã§ãã¨ããä¸éã§ããæåã¯è¡¨ç¤ºæ°éã®1/2ã1/3ç¨åº¦ããèããã¨å®å¨ã§ãã</li></ul></section>
<section class="guide-section"><h2>è²·ããªãæ¡ä»¶</h2><ul><li>ð´ è¦éããåèå¤è¡¨ç¤ºãç´è¿æåãã¼ã¿è¡¨ç¤ºãRRãæªããRSIéç±ãã¬ã¸ã¹ã¿ã³ã¹ç´åããã©ãé«ããããåºæ¥é«ãå¼±ãå ´åã¯åºæ¬çã«è¦éãåªåã§ãã</li><li>è¿·ã£ãã¨ãã¯å¥ããªãããã£ã³ã¹ã¯ä½åº¦ã§ãæ¥ã¾ãããè³éã¯å®ãå¿è¦ãããã¾ãã</li></ul></section>
<section class="guide-section"><h2>å®æ¦ãã§ãã¯ãªã¹ã</h2><ul><li>1. ãã¼ã¿ããªã¢ã«ã¿ã¤ã ãç¢ºèª</li><li>2. å¤å®ãð¢ã¾ãã¯ð¡ãç¢ºèª</li><li>3. ã¨ã³ããªã¼æ ¹æ ãèª­ã</li><li>4. æ³¨æç¹ãè´å½çã§ãªããç¢ºèª</li><li>5. RRãæªãããªããç¢ºèª</li><li>6. æåãä½ç½®ãç¢ºèª</li><li>7. æ¨å¥¨æ°éä»¥ä¸ãã§ããã°ååä»¥ä¸ã§æ¤è¨</li></ul></section>`;
  const root = document.createElement('div');
  root.id = 'dashboard-guide-widget';
  root.innerHTML = `<style>${css}</style><button class="guide-fab" type="button">ï¼ ä½¿ãæ¹</button><div class="guide-backdrop" role="dialog" aria-modal="true" aria-label="ããã·ã¥ãã¼ãã®è¦æ¹"><div class="guide-modal"><div class="guide-head"><strong>BTC/JPY ããã·ã¥ãã¼ãã®è¦æ¹</strong><button class="guide-close" type="button">éãã</button></div><div class="guide-body"><p class="guide-note">å¤å®ã»æ ¹æ ã»æåãã»å©ç¢ºãå·éã«ç¢ºèªããããã®ã¬ã¤ãã§ããæè³å¤æ­ãä¿è¨¼ãããã®ã§ã¯ããã¾ããã</p>${html}<a class="guide-link" href="guide.html" target="_blank" rel="noopener">å¥ãã¼ã¸ã§éã â</a></div></div></div>`;
  document.body.appendChild(root);
  const backdrop = root.querySelector('.guide-backdrop');
  root.querySelector('.guide-fab').addEventListener('click', () => backdrop.style.display = 'flex');
  root.querySelector('.guide-close').addEventListener('click', () => backdrop.style.display = 'none');
  backdrop.addEventListener('click', e => { if (e.target === backdrop) backdrop.style.display = 'none'; });
  document.addEventListener('keydown', e => { if (e.key === 'Escape') backdrop.style.display = 'none'; });
})();